/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1accecc1ab16b6333a7e920cb0a06578)
interface __BaseEnv_Env {
	TREASURE_ROOMS: KVNamespace;
	ENVIRONMENT: "production" | "development";
	ROOMS: DurableObjectNamespace<import("./treasure-room-worker").TreasureRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./treasure-room-worker");
		durableNamespaces: "TreasureRoom";
	}
	interface ProductionEnv {
		TREASURE_ROOMS: KVNamespace;
		ENVIRONMENT: "production";
		ROOMS: DurableObjectNamespace<import("./treasure-room-worker").TreasureRoom>;
	}
	interface DevelopmentEnv {
		TREASURE_ROOMS: KVNamespace;
		ENVIRONMENT: "development";
		ROOMS: DurableObjectNamespace<import("./treasure-room-worker").TreasureRoom>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
