name = "ff14-tw-treasure"
main = "treasure-room-worker.js"
compatibility_date = "2024-01-01"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# KV namespace 設定（預設環境：用於 wrangler dev 和預覽環境）
[[kv_namespaces]]
binding = "TREASURE_ROOMS"
id = "81b924a9a6f347fc96bf2b439d0dc2d6"
preview_id = "LOCAL_KV_NAMESPACE"  # 用於 `wrangler dev --local` 本地開發

# 本地開發設定
[dev]
port = 8787
local_protocol = "http"

[env.production]
name = "ff14tw-treasure-room-api"
route = { pattern = "api.ff14.tw/*", zone_name = "ff14.tw", custom_domain = true }

[env.development]
name = "ff14tw-treasure-room-api-dev"
